package org.elearning.backend.content.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


import java.time.LocalDateTime;
import java.util.UUID;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor

//Lesson Entity class, referencing the table "lessons" from the sql table

@Entity
@Table(name = "lessons")
public class Lesson {

    //Id is randomly generated by default
    @Id
    @Column(name="id")
    @GeneratedValue
    private UUID id;

    //The commented lines can be uncommented once the Chapter classes are done
    //The code seems to work fine in its current state as well, but the second option might be preferred
    //Foreign Key to the "chapter" table, cannot be null

    //@ManyToOne
    //@JoinColumn(name = "chapter_id", nullable = false)
    //private Chapter chapterID;

    @Column(name="chapter_id", nullable = false)
    private UUID chapterID;

    //Lesson Title. Cannot be null

    @NotNull
    @Column(name="title")
    private String title;

    //Markdown content in Lesson
    @Column(name="content_md")
    private String contentMarkdown;

    //Lesson order inside a chapter. 0 by default.
    @NotNull
    @Column(name="order_index")
    private int orderIndex = 0;

    //Time of creation of the Lesson. Coincides with the time the table was created by default
    @NotNull
    @Column(name="created_at")
    private LocalDateTime createdAt = LocalDateTime.now();

    //Time of the last update. By default, it coincides with the time the table was created.
    @NotNull
    @Column(name="updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();

    //Makes sure to update the time of the last update with each modification
    @PreUpdate
    public void preUpdate(){
        this.updatedAt = LocalDateTime.now();
    }


}
