spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/adaptive_tutor
    username: user
    password: password
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8067
